name: Terraform CI/CD Pipeline

on:
push:
branches:
- main

permissions:
id-token: write
contents: read

jobs:
terraform:
runs-on: self-hosted

```
steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Test
    run: |
      echo "Runner Working"
      pwd
```
